# SRAMS PostgreSQL Configuration Generator
# Generates .env file in ProgramData (professional pattern)

param(
    [Parameter(Mandatory = $true)]
    [string]$InstallPath,
    
    [Parameter(Mandatory = $true)]
    [string]$DbPassword,
    
    [Parameter(Mandatory = $true)]
    [string]$JwtSecret,
    
    [Parameter(Mandatory = $true)]
    [string]$AdminEmail,
    
    [Parameter(Mandatory = $true)]
    [string]$AdminPassword,
    
    [Parameter(Mandatory = $true)]
    [string]$AdminName
)

$ErrorActionPreference = "Stop"

Write-Host "Generating SRAMS configuration..." -ForegroundColor Cyan

# ProgramData paths (writable by services)
$programData = "C:\ProgramData\SRAMS"
$configPath = Join-Path $programData "config"
$documentsPath = Join-Path $programData "documents"
$logsPath = Join-Path $programData "logs"

# Create all required directories
foreach ($dir in @($programData, $configPath, $documentsPath, $logsPath)) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "  Created: $dir" -ForegroundColor Gray
    }
}

# Also create config in install path (temporary, for installer to find)
$installConfigPath = Join-Path $InstallPath "config"
if (-not (Test-Path $installConfigPath)) {
    New-Item -ItemType Directory -Path $installConfigPath -Force | Out-Null
}

# Generate .env file content
$envContent = @"
# SRAMS Enterprise - PostgreSQL Configuration
# Generated by installer on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Database Type
DB_TYPE=postgres

# PostgreSQL Connection
DB_HOST=localhost
DB_PORT=5432
DB_NAME=srams
DB_USER=srams_app
DB_PASSWORD=$DbPassword
DB_SSLMODE=disable
DB_MAX_CONNS=25
DB_MIN_CONNS=5

# JWT Configuration
JWT_SECRET=$JwtSecret
JWT_EXPIRES_IN=15m
REFRESH_TOKEN_EXPIRES_IN=168h

# Server Configuration
SERVER_PORT=8080
SERVER_HOST=localhost

# Paths (using ProgramData for data files)
DOCUMENTS_PATH=$documentsPath
LOGO_PATH=$documentsPath\logo

# Security
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW=1m
MAX_LOGIN_ATTEMPTS=5
LOCKOUT_DURATION=30

# CORS Origins
CORS_ORIGINS=http://localhost:3000,http://localhost:5173

# PostgreSQL Directory (binaries in Program Files)
PG_DIR=$InstallPath\pgsql
PG_DATA=C:\ProgramData\SRAMS\postgres

# Super Admin credentials (used by setup script)
ADMIN_EMAIL=$AdminEmail
ADMIN_PASSWORD=$AdminPassword
ADMIN_FULL_NAME=$AdminName
"@

# Write to BOTH locations
$envFileProgramData = Join-Path $configPath ".env"
$envFileInstall = Join-Path $installConfigPath ".env"

Set-Content -Path $envFileProgramData -Value $envContent -Encoding UTF8
Set-Content -Path $envFileInstall -Value $envContent -Encoding UTF8

Write-Host "Configuration saved to:" -ForegroundColor Green
Write-Host "  $envFileProgramData" -ForegroundColor Gray
Write-Host "  $envFileInstall" -ForegroundColor Gray

# Save admin credentials separately for setup script
$adminFile = Join-Path $configPath "admin-setup.json"
$adminJson = @{
    email     = $AdminEmail
    password  = $AdminPassword
    full_name = $AdminName
} | ConvertTo-Json

Set-Content -Path $adminFile -Value $adminJson -Encoding UTF8

Write-Host "Admin credentials saved for initial setup" -ForegroundColor Green
Write-Host "Configuration complete!" -ForegroundColor Cyan
